# Generated by Django 4.0.2 on 2022-02-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_competition_type_of_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='competition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.competition'),
        ),
    ]
