# Generated by Django 4.0.2 on 2022-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_score_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_user', to='api.user'),
        ),
    ]
