# Generated by Django 4.0.2 on 2022-02-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_score_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['score']},
        ),
    ]
